feat: canvas implementation
Yannic-reust/polyslope pull request #16
Opened 2023-11-10 15:05 UTC by Cyril676

Fixed #15

2023-11-14 09:59 UTC, Yannic-reust commented on src/components/Canvas/Canvas.jsx
> +                    position: "absolute"}}>
please use css classes from tailwind, so the project is coherent

2023-11-15 10:23 UTC, DerBeton approved these changes
I pushed a new commit which adds the tailwind classes for the "canvas-container" and removed downscaling for the landscape. I think it's better to use the default scales from our models so we don't have to scale down every object we are going to import in the future.

Great work 👍  You can merge those changes.

2023-11-15 10:23 UTC, DerBeton commented on src/components/Canvas/Canvas.jsx
> +                />
Good idea to limit the amount of zoom and angle.

2023-11-15 17:02 UTC, Cyril676 commented on src/components/Canvas/Canvas.jsx
> +                    position: "absolute"}}>
Thanks for the review! I forgot to change the styles back to tailwind css after we found the issue with the width of the element. And just for clarification, you already applied the changes with the new commit so I can just merge it now? And yes removing the scaling is a good idea as well, that was just for me while testing

2023-11-15 17:25 UTC, DerBeton commented on src/components/Canvas/Canvas.jsx
> +                    position: "absolute"}}>
Great, yeah I already commited the changes so you can merge this request.

2023-11-15 21:19 UTC, DerBeton requested changes
Added comment for level of detail.

2023-11-15 21:19 UTC, DerBeton commented on src/components/Canvas/Canvas.jsx
> +                <Detailed distances={[0, 450, 600]}>
```suggestion
                <Detailed distances={[0, 4500, 6000]}>
```
Detailed amount has to be changed since map is not scaled down anymore.

2023-11-19 18:42 UTC, merged